### ISSUE TITLE
Links generated by TOC plugin replacing original URL instead

### ISSUE THREAD

**Issue by chuajiaxuan** [nus-mtp/lecture-note-2.0#197] opened 2017-02-28 05:35 UTC
Clicking on the links for the TOC will cause "localhost:8080/#/content" to be replaced as "localhost:8080/#/" + header name (e.g. "Header1").

**Comment by amoshydra** [comment] 2017-03-02 08:22
Duplicate of #189

**Closed as completed by amoshydra** 2017-03-02 08:22 UTC
Labels: bug, duplicate
